# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "152ad4ed3578c6f1d516e8e84bc76178"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "Unmute Editor"
handle = "unmute-editor-app"

[build]
dev_store_url = "unmuteframes.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
